export function aboutUs() {
  <>
    <Head>
      <title>Crypie - About us</title>
      <meta name="description" content="Generated by Crypie" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.Main}></main>
  </>;
}
