import Head from "next/head";
import Layout from "@/components/layout";
import styles from "../styles/pages/aboutUs.module.scss";

export default function aboutUs() {
  return (
    <>
      <Head>
        <title>Crypie - About us</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <Layout>
          <h1>About us</h1>
          <div className={styles.content}>
            <div className={styles.aboutCard}>
              <div className={styles.myImage}>
                <img src="https://picsum.photos/1080/1080" alt="myImage" />
              </div>
              <h3 className={styles.myName}>Pippo De Pippis</h3>
              <div className={styles.info}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  asperiores enim non id ratione maxime nesciunt. Officia,
                  sapiente? Nostrum ab at repellendus eos exercitationem veniam.
                </p>
              </div>
              <div className={styles.contacts}>
                <ul>
                  <li>
                    <span>Linkedin</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Github</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Mail</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.aboutCard}>
              <div className={styles.myImage}>
                <img src="https://picsum.photos/1080/1080" alt="myImage" />
              </div>
              <h3 className={styles.myName}>Pippo De Pippis</h3>
              <div className={styles.info}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  asperiores enim non id ratione maxime nesciunt. Officia,
                  sapiente? Nostrum ab at repellendus eos exercitationem veniam.
                </p>
              </div>
              <div className={styles.contacts}>
                <ul>
                  <li>
                    <span>Linkedin</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Github</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Mail</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.aboutCard}>
              <div className={styles.myImage}>
                <img src="https://picsum.photos/1080/1080" alt="myImage" />
              </div>
              <h3 className={styles.myName}>Pippo De Pippis</h3>
              <div className={styles.info}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  asperiores enim non id ratione maxime nesciunt. Officia,
                  sapiente? Nostrum ab at repellendus eos exercitationem veniam.
                </p>
              </div>
              <div className={styles.contacts}>
                <ul>
                  <li>
                    <span>Linkedin</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Github</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Mail</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.aboutCard}>
              <div className={styles.myImage}>
                <img src="https://picsum.photos/1080/1080" alt="myImage" />
              </div>
              <h3 className={styles.myName}>Pippo De Pippis</h3>
              <div className={styles.info}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  asperiores enim non id ratione maxime nesciunt. Officia,
                  sapiente? Nostrum ab at repellendus eos exercitationem veniam.
                </p>
              </div>
              <div className={styles.contacts}>
                <ul>
                  <li>
                    <span>Linkedin</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Github</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Mail</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.aboutCard}>
              <div className={styles.myImage}>
                <img src="https://picsum.photos/1080/1080" alt="myImage" />
              </div>
              <h3 className={styles.myName}>Pippo De Pippis</h3>
              <div className={styles.info}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  asperiores enim non id ratione maxime nesciunt. Officia,
                  sapiente? Nostrum ab at repellendus eos exercitationem veniam.
                </p>
              </div>
              <div className={styles.contacts}>
                <ul>
                  <li>
                    <span>Linkedin</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Github</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                  <li>
                    <span>Mail</span>
                    <span className={styles.link}>
                      <a href="#">LINK</a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
