import { useState } from "react";
import Head from "next/head";
import Layout from "@/components/layout";
import { mockUser } from "./api/mockUser";
import styles from "../styles/pages/account.module.scss";

export default function account() {
  const mode = "dark_mode";
  const { username, email, password } = mockUser;

  return (
    <>
      <Head>
        <title>Crypie - Cripto account</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={mode}>
        <Layout>
          <h2>Hi, {username}!</h2>
          <div className={styles.settingList}>
            <div className={styles.userSettings}>
              <img
                className={styles.userPhoto}
                src="https://robohash.org/user?set=set4"
              />
              <div className={styles.userData}>
                <h2 className={styles.userSettingsTitle}>Your info</h2>
                <p>Username: {username}</p>
                <p>Email: {email}</p>
                <p>Password: {password}</p>
              </div>
              <button className={styles.editBtn}>
                <h3>Edit</h3>
              </button>
            </div>
            <div className={styles.cardSettings}>
              <h2 className={styles.cardSettingsTitle}>Your cards</h2>

              {/* credit card */}

              <div className={styles.card}>
                <div className={`${styles.cardFront} ${styles.cardPart}`}>
                  <p className={styles.cardNum}>**** **** **** 6258</p>
                  <div className={styles.userName}>
                    <span className={styles.cardLabel}>Card holder</span>
                    <p className={styles.cardInfo}>John Doe</p>
                  </div>
                  <div className={styles.cardExpiration}>
                    <span className={styles.cardLabel}>Expires</span>
                    <p className={styles.cardInfo}>10/25</p>
                  </div>
                </div>

                <div className={`${styles.cardBack} ${styles.cardPart}`}>
                  <div className={styles.blackLine}></div>
                  <div className={styles.Content}>
                    <div className={styles.cardSecret}>
                      <p className={styles.secretNum}>420</p>
                    </div>
                  </div>
                </div>
              </div>
              {/* end card */}
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
