import Head from "next/head";
import Layout from "@/components/layout";


export default function account() {
  const mode = "dark_mode";
  return (
    <>
      <Head>
        <title>Crypie - Cripto account</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={mode}>
        <Layout>
          <h2>  account </h2>
        </Layout>
      </main>
    </>
  );
}
