import LoginForm from "@/components/login_Form";
import Head from "next/head";
import styles from "@/styles/pages/Login.module.scss";




export default function login() {

  return (
    <>
      <Head>
        <title>Crypie - Cripto Wallet Accedi</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <div className={styles.container}>
          <h1>
            Crypie
          </h1>
          <LoginForm />
        </div>
      </main>
    </>
  );
}
