import Head from "next/head";
import Layout from "@/components/layout";
import CakeChart from "@/components/cakeChart";
import WalletList from "@/components/walletList";
import styles from "@/styles/pages/wallet.module.scss";
import { summArrayValues } from "@/utils/func";
import { useState, useEffect, useContext } from "react";
import { Context } from "@/store";

export default function Wallet() {
  const [walletInLocalStorage, setWalletInLocalStorage] = useState();

  useEffect(() => {
    dispatch({ type: "SELECTED_ICON", payload: "wallet" });
  }, []);

  useEffect(() => {
    setWalletInLocalStorage(
      typeof window !== "undefined"
        ? JSON.parse(localStorage.getItem("wallet"))
        : []
    );
  }, []);

  let value = 0;
  const cakePercentualArray = walletInLocalStorage?.map(
    (item) => (value = item.qty * item.price)
  );

  const { state, dispatch } = useContext(Context);

  return (
    <>
      <Head>
        <title>Crypie - Cripto Wallet</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <Layout theme={state.modeData}>
          <div className={styles.Content}>
            <h2 className={styles.title}> MY WALLET STATUS</h2>

            {walletInLocalStorage ? (
              <>
                <div className={styles.chartArea}>
                  <CakeChart
                    cakePercentualArray={cakePercentualArray}
                    chartData={walletInLocalStorage}
                  />
                  <h3 className={styles.walletValue}>
                    WALLET VALUE: € {summArrayValues(cakePercentualArray)}
                  </h3>
                </div>

                <div className={styles.walletList}>
                  <h2> Crypto </h2>
                  <WalletList data={walletInLocalStorage} />
                </div>
              </>
            ) : (
              <h5>Buy a crypto, it will be showed here</h5>
            )}
          </div>
        </Layout>
      </main>
    </>
  );
}
