import Head from "next/head";
import Layout from "@/components/layout";
import { useContext, useState } from "react";
import CardsList from "@/components/cards_list";
import styles from "../styles/pages/watchlist.module.scss";
import Button from "@/components/button";
import SwitcherTheme from "@/components/switcher-theme";
import { Context } from "@/store";

export default function watchlist() {
  const [isSwitcherTheme, setIsSwitcherTheme] = useState(true);
  const [isLightActive, setLightActive] = useState(true);
  const onHandleChangeTheme = () => {
    setIsSwitcherTheme((prev) => !prev);
  };

  const { state, dispatch } = useContext(Context);

  const [coin, setCoin] = useState(
    typeof window !== "undefined"
      ? localStorage.getItem("watchlist")
        ? JSON.parse(localStorage.getItem("watchlist"))
        : []
      : []
  );
  let stars = [];
  if (coin) {
    stars = state.cryptoListData.filter((crypto) => coin.includes(crypto.id));
  }

  return (
    <>
      <Head>
        <title>Crypie - Cripto watchlist</title>
        <meta name="description" content="Generated by Crypie" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout theme={isSwitcherTheme}>
          
          <h2> watchlist </h2>
          <div className={styles.watchlist}>
            {stars.length > 0 ? (
              <CardsList data={stars} />
            ) : (
              <h5>Add an element in your watchlist, it will be showed here.</h5>
            )}
          </div>
          <SwitcherTheme status={isLightActive} func={onHandleChangeTheme} />
        </Layout>
      </main>
    </>
  );
}
